### ISSUE TITLE
Started generating empty svgs

### ISSUE THREAD

**Issue by promptgoblin** [karalabe/burntpix-benchmark#1]
All of my scripts started generating empty svgs since last night.  I tested the evm commands manually and see the same results.

Previously, I had run through 100k svgs at least to 250k-1M iterations.  No issues.  Nothing in any of my scripts changed.

Rebuilt my environment.  Reinstalled geth, etc.  Same result.  Not sure if an external dependency has changed - but I notice the burntpix.com simulator still works, so maybe not.

Instant results, no svg produced any time I run the command - including your sample here to be 100% sure I'm not doing something wrong:

*$ evm run --prestate ./genesis.json --receiver 0x49206861766520746F6F206D7563682074696D65  --input 0xa4de9ab40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007A120
INFO [02-23|11:17:32.869] Persisted trie from memory database      nodes=10 size=1.20KiB time="16.08µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=0 livesize=0.00B

---
evm version 1.13.13-stable-7f131dcb

Linux 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

**Comment by Gemdetector** [comment]
I have the same issue, tried it on JS and on PY. On both I get a empty svg

**Comment by promptgoblin** [comment]
I built two new VMs on different machines and started from scratch.  Same issue on both (runs in microseconds, empty svg file) while running the command manually to keep it as simple as possible.  Not sure if this is trying to talk to an oracle or other dependency that is unavailable - or if I'm just crazy =)  It runs so fast, I can't tell if it's making any network connections though.

**Comment by promptgoblin** [comment]
Actually getting this:  error: invalid opcode: PUSH0

Spun up another VM and built goeth from source code and still the same issue.

**Comment by lyfsn** [comment]
I encountered the same issue: `error: invalid opcode: PUSH0`.

Additionally, when initializing a new Ethereum network and using this script to call a contract method, I got `execution reverted`. How can I fix it?

```
const { ethers } = require('ethers');
const { JsonRpcProvider } = ethers;

const rpcUrl = 'http://127.0.0.1:49851';
const provider = new JsonRpcProvider(rpcUrl);

const privateKey = '0x0000';
const wallet = new ethers.Wallet(privateKey, provider);

const contractAddress = '0x49206861766520746f6f206d7563682074696d65';
const contractABI = [
  'function run(uint32 seed, uint256 iteration) external returns (string)'
];

const contract = new ethers.Contract(contractAddress, contractABI, wallet);

async function callRunMethod() {
  const seed = 0x0000000000000000000000000000000000000000000000000000000000000000
  const iteration = 0x000000000000000000000000000000000000000000000000000000000007A120

  try {
    const result = await contract.run.staticCall(seed, iteration);
    console.log('Result:', result);
  } catch (error) {
    console.error('Error:', error);
  }
}


callRunMethod();
```
The error log:
```
Error: Error: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0xa4de9ab40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007a120", "from": "0x8943545177806ED17B9F23F0a21ee5948eCaa776", "to": "0x49206861766520746f6F206D7563682074696D65" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.12.1)
    at makeError (/Volumes/T7/work/fsn/benchmarks/test-burntpix/sdk/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at getBuiltinCallException (/Volumes/T7/work/fsn/benchmarks/test-burntpix/sdk/node_modules/ethers/lib.commonjs/abi/abi-coder.js:105:37)
    at AbiCoder.getBuiltinCallException (/Volumes/T7/work/fsn/benchmarks/test-burntpix/sdk/node_modules/ethers/lib.commonjs/abi/abi-coder.js:206:16)
    at JsonRpcProvider.getRpcError (/Volumes/T7/work/fsn/benchmarks/test-burntpix/sdk/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:668:43)
    at /Volumes/T7/work/fsn/benchmarks/test-burntpix/sdk/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:302:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'CALL_EXCEPTION',
  action: 'call',
  data: null,
  reason: null,
  transaction: {
    to: '0x49206861766520746f6F206D7563682074696D65',
    data: '0xa4de9ab40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007a120',
    from: '0x8943545177806ED17B9F23F0a21ee5948eCaa776'
  },
  invocation: null,
  revert: null,
  shortMessage: 'missing revert data',
  info: {
    error: { code: -32000, message: 'execution reverted' },
    payload: { method: 'eth_call', params: [Array], id: 2, jsonrpc: '2.0' }
  }
}
```

**Comment by lyfsn** [comment]
Using Geth version 1.13.11 or earlier is okay.

**Comment by lyfsn** [comment]
This PR will fix the problem: https://github.com/ethereum/go-ethereum/pull/29896
